language: python
python:
  - 2.7
before_install:
  - cd frontend && npm install
  - npm install -g grunt-cli
install:
  - pip install -r dev_requirements.txt
  - pip install -e .
before_script:
  - py.test -vvrs
  - flake8
script:
  - cd frontend && grunt jshint
notifications:
  irc:
    channels:
      - "chat.freenode.net#etherex-dev"
    use_notice: true
    skip_join: true
